---
title: "s2bix_morphometa"
author: "Daniel"
date: "2024-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(ggstatsplot)
library(viridis)
```

red quant
```{r}
# make a list of all csvs that end in ""hom red quant raw.csv"" in the directory and subdirectories
homredquantl <- list.files(pattern = "s2b hom red quant raw.csv$", recursive = TRUE)
#read them into one dataframes
homredquant <- read_csv(homredquantl)
colnames(homredquant)[colnames(homredquant)=='%Area'] <-"Area"
homredquant <- homredquant$Area

# make a list of all csvs that end in ""wts red quant raw.csv"" in the directory and subdirectories
wtsredquantl <- list.files(pattern = "s2b wts red quant raw.csv", recursive = TRUE)
#read them into one dataframe
wtsredquant <- read_csv(wtsredquantl)
colnames(wtsredquant)[colnames(wtsredquant)=='%Area'] <-"Area"
wtsredquant <- wtsredquant$Area

# make a list of all csvs that end in ""het red quant raw.csv"" in the directory and subdirectories
hetredquantl <- list.files(pattern = "s2b het red quant raw.csv$", recursive = TRUE)
#read them into one dataframes
hetredquant <- read_csv(hetredquantl)
colnames(hetredquant)[colnames(hetredquant)=='%Area'] <-"Area"
hetredquant <- hetredquant$Area

# combining the dataframes and then pivoting to te right format for violin plotting 

max_ln <- max(c(length(homredquant), length(hetredquant), length(wtsredquant))) 
redquant<- data.frame("cStag2b hom mutant" = c(homredquant,rep(NA, max_ln - length(homredquant))), 
                      "bStag2b het mutant" = c(hetredquant,rep(NA, max_ln - length(hetredquant))), 
                      "aWild type" = c(wtsredquant,rep(NA, max_ln - length(wtsredquant))))
redquant <- pivot_longer(redquant, cols = 1:3)
## really ugly way of fixing the no special characters in column names by changing them after pivoting the table 
redquant$name <- str_replace_all(redquant$name, ".hom.mutant","-/-")
redquant$name <- str_replace_all(redquant$name, ".het.mutant","+/-")
redquant$name <- str_replace_all(redquant$name, "Wild.type","Stag2b+/+")
```

plotting and saving
```{r}

plt2 <- ggbetweenstats(
  data = redquant,
  x = name,
  y = value,
  pairwise.display = "all",
  p.adjust.method = "none",
  centrality.point.args = list(size = 5, color = "black"),
  bf.message = F,
  point.args = list(position = ggplot2::position_jitterdodge(dodge.width = 0.6), alpha =
    0.6, size = 3, stroke = 0, na.rm = TRUE ),
  palette = "Dark2"
)
plt2 <- plt2 + 
  # Add labels and title
  labs(
    x = "Genotype",
    y = "Percent Area Alizarin Red (%)",
    title = ""
  ) + theme(axis.text=element_text(size=14),
        axis.title=element_text(size=14,face="bold"))
plt2
#save the plot

ggsave(
  "s2bix red quant violin.png",
  plt2,
  dpi = 500
)
```

```{r}

# Red Quant
p<-ggplot(redquant, aes(x=name, y=value, fill=name)) +
  geom_violin(trim=T, linewidth=1)
ggsave(
  "s2bix_redquant_violin_clean.pdf",
  p +scale_fill_manual(values=c("grey","#99ffff","#9999FF"))+ theme_classic()+theme(legend.position="none") +geom_boxplot(width=0.1, linewidth=1)+ theme(axis.line = element_line(size = 1, linetype = "solid"))+labs(x = "Genotype", y= "Coverage alizarin red (%)")
  +ylim(0,5),
  dpi = 300,
  units = c("mm"),
  width = 70,
  height = 70
)
```

